import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: "1rem", sm: "1.5rem", lg: "2rem" },
    },
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--border)",
        ring: "var(--accent)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "#1D9E75",
          hover: "#178a64",
          foreground: "#ffffff",
          subtle: "#e6f7f2",
          "50":  "#e6f7f2",
          "100": "#b3e8d8",
          "200": "#80d9be",
          "300": "#4dcaa4",
          "400": "#26b88e",
          "500": "#1D9E75",
          "600": "#178a64",
          "700": "#117553",
          "800": "#0b6042",
          "900": "#054b31",
        },
        secondary: {
          DEFAULT: "#378ADD",
          hover: "#2a72c4",
          foreground: "#ffffff",
          subtle: "#e8f2fb",
          "50":  "#e8f2fb",
          "100": "#c0d9f5",
          "200": "#98c0ef",
          "300": "#70a7e9",
          "400": "#4e91e3",
          "500": "#378ADD",
          "600": "#2a72c4",
          "700": "#1e5aab",
          "800": "#134292",
          "900": "#082a79",
        },
        danger: {
          DEFAULT: "#E24B4A",
          hover: "#cc3a39",
          foreground: "#ffffff",
          subtle: "#fdeaea",
          "50":  "#fdeaea",
          "100": "#f9c4c4",
          "200": "#f59e9e",
          "300": "#f17878",
          "400": "#ed5858",
          "500": "#E24B4A",
          "600": "#cc3a39",
          "700": "#b62928",
          "800": "#a01817",
          "900": "#8a0706",
        },
        warning: {
          DEFAULT: "#EF9F27",
          hover: "#d98a18",
          foreground: "#7c4a00",
          subtle: "#fef6e8",
          "50":  "#fef6e8",
          "100": "#fde4b8",
          "200": "#fbd288",
          "300": "#f9c058",
          "400": "#f7b038",
          "500": "#EF9F27",
          "600": "#d98a18",
          "700": "#c37509",
          "800": "#ad6000",
          "900": "#974b00",
        },
        success: {
          DEFAULT: "#639922",
          hover: "#538219",
          foreground: "#ffffff",
          subtle: "#eef6e2",
          "50":  "#eef6e2",
          "100": "#cfe8a8",
          "200": "#b0da6e",
          "300": "#91cc34",
          "400": "#7ab428",
          "500": "#639922",
          "600": "#538219",
          "700": "#436b10",
          "800": "#335407",
          "900": "#233d00",
        },
        destructive: { DEFAULT: "#E24B4A", foreground: "#ffffff" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          subtle: "var(--accent-subtle)",
          foreground: "var(--accent-foreground)",
        },
        card: { DEFAULT: "var(--surface)", foreground: "var(--foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        sidebar: {
          bg: "var(--sidebar-bg)",
          border: "var(--sidebar-border)",
          text: "var(--sidebar-text)",
          muted: "var(--sidebar-text-muted)",
          active: "var(--sidebar-active-text)",
          "active-bg": "var(--sidebar-active-bg)",
          hover: "var(--sidebar-hover-bg)",
        },
        navy: {
          50: "var(--navy-50)", 100: "var(--navy-100)", 200: "var(--navy-200)",
          300: "var(--navy-300)", 400: "var(--navy-400)", 500: "var(--navy-500)",
          600: "var(--navy-600)", 700: "var(--navy-700)", 800: "var(--navy-800)",
          900: "var(--navy-900)", 950: "var(--navy-950)",
        },
        "health-green": {
          50: "var(--health-green-50)", 100: "var(--health-green-100)",
          300: "var(--health-green-300)", 400: "var(--health-green-400)",
          500: "var(--health-green-500)", 600: "var(--health-green-600)",
          700: "var(--health-green-700)", 800: "var(--health-green-800)",
          900: "var(--health-green-900)",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)", DEFAULT: "var(--radius)", md: "var(--radius-md)",
        lg: "var(--radius-lg)", xl: "var(--radius-xl)", "2xl": "var(--radius-2xl)", full: "var(--radius-full)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      spacing: {
        "sidebar": "16rem",
        "sidebar-collapsed": "4.5rem",
        "topbar": "4rem",
      },
      keyframes: {
        fadeUp: { from: { transform: "translateY(16px)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        scaleIn: { from: { transform: "scale(0.95)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        pulseSlow: { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.4" } },
      },
      animation: {
        "fade-up": "fadeUp 0.4s ease forwards",
        "fade-in": "fadeIn 0.3s ease forwards",
        "scale-in": "scaleIn 0.2s ease forwards",
        "shimmer": "shimmer 1.5s infinite",
        "pulse-slow": "pulseSlow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
